### ISSUE TITLE
ModuleNotFoundError while running project

### ISSUE THREAD

**Issue by mayurilahane** [paint-it/genpass#57]
- OS: Fedora 31
- Python Version: 3.6 or 3.7

- Error:
```
(env36) [mlahane@localhost pygenpass]$ pygenpass
Traceback (most recent call last):
  File "/home/mlahane/pygenpass/env36/bin/pygenpass", line 11, in <module>
    load_entry_point('pygenpass==0.2.dev27+ge6c5eed', 'console_scripts', 'pygenpass')()
  File "/home/mlahane/pygenpass/env36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mlahane/pygenpass/env36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/mlahane/pygenpass/env36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/mlahane/pygenpass/env36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/mlahane/pygenpass/env36/lib/python3.6/site-packages/pygenpass-0.2.dev27+ge6c5eed-py3.6.egg/pygenpass/__init__.py", line 24, in <module>
    from pygenpass.password import createpass
  File "/home/mlahane/pygenpass/env36/lib/python3.6/site-packages/pygenpass-0.2.dev27+ge6c5eed-py3.6.egg/pygenpass/password.py", line 24, in <module>
    from pygenpass.database import DatabaseConnection
  File "/home/mlahane/pygenpass/env36/lib/python3.6/site-packages/pygenpass-0.2.dev27+ge6c5eed-py3.6.egg/pygenpass/database.py", line 23, in <module>
    import sqlite3  # library for database
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by mayurilahane** [comment]
**working fine on 3.7** for me!
But not on 3.6
anyone can recheck for both versions?
@ganeshhubale @chitalekunal @	Yadnyawalkya

**Comment by ganeshhubale** [comment]
@mayurilahane It works on my system with Fedora 29 and python3.

**Comment by mayurilahane** [comment]
okay then thanks @ganeshhubale
