### ISSUE TITLE
Validation not working  and exception handling

### ISSUE THREAD

**Issue by chitalekunal** [paint-it/genpass#60]
(env) kunal@kunal-debian:~/pygenpass$ pygenpass savepass
Enter portal name [None]: abc
Enter your password [None]: 
Enter email id [None]: abc@abc
Enter portal url [None]: abcAba
Traceback (most recent call last):
  File "/home/kunal/env/bin/pygenpass", line 11, in <module>
    load_entry_point('pygenpass==0.0.0', 'console_scripts', 'pygenpass')()
  File "/home/kunal/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kunal/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kunal/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kunal/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kunal/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kunal/env/lib/python3.5/site-packages/pygenpass-0.0.0-py3.5.egg/pygenpass/password.py", line 89, in savepass
    portal_url=portal_url,
  File "/home/kunal/env/lib/python3.5/site-packages/pygenpass-0.0.0-py3.5.egg/pygenpass/database.py", line 53, in insert_data
    (self.portal_name, self.password, self.creation_date, self.email, self.portal_url,),
sqlite3.IntegrityError: UNIQUE constraint failed: passwords.portal_name

**Comment by mayurilahane** [comment]
Done!
