### ISSUE TITLE
Few suggestions in pygenpass existing behavior

### ISSUE THREAD

**Issue by Yadnyawalkya** [paint-it/genpass#64]
These suggestions are really what I think it should do. Feel free to discuss doubts here.

`<STRONG OPINIONS AHEAD/>`

**1. Remove `pass` suffix from all existing arguments**

When you run commands like `pygenpass allpass` for example, we already know we are talking about password since `pygenpass` already got that `pass` suffix. You can simply put an argument like `all` (instead of `allpass`) so the user should just type as minimal as he/she can, for example, `pygenpass all`.

all, create, add (check 5 before this change), copy (check 8 for more info), show, modify, delete, version

**2. Meaningful messages after every action completion**

For example: 

```
(py3) [ytale@localhost pygenpass]$ pygenpass createpass
Enter portal name [None]: 
Enter email id [None]: 
Enter portal url [None]: 
(py3) [ytale@localhost pygenpass]$ 
```

Got one more example: 

```
(py3) [ytale@localhost pygenpass]$ pygenpass createpass
Enter portal name [None]: 
Enter email id [None]: 
Enter portal url [None]: 
Traceback (most recent call last):
  File "/home/ytale/opensource/py3/bin/pygenpass", line 11, in <module>
    load_entry_point('pygenpass==0.1', 'console_scripts', 'pygenpass')()
  File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ytale/opensource/py3/lib/python3.7/site-packages/pygenpass-0.1-py3.7.egg/pygenpass/password.py", line 106, in createpass
    portal_url=portal_url,
  File "/home/ytale/opensource/py3/lib/python3.7/site-packages/pygenpass-0.1-py3.7.egg/pygenpass/database.py", line 53, in insert_data
    (self.portal_name, self.password, self.creation_date, self.email, self.portal_url,),
sqlite3.IntegrityError: UNIQUE constraint failed: passwords.portal_name
```
(Did not searched afterwards, please check if you find more)

You should put a message as `Password saved successfully!` at the end (May be in different color!? That would be 

**3. No validation require**

https://github.com/paint-it/pygenpass/issues/45#issuecomment-578410599

**4. Table related improvements**

- Proper table printing -- https://github.com/paint-it/pygenpass/issues/59
- Limit table wrapping till least length of the password so that password would be in single line (the only thing I want to say is -- user should copy password by double click highlighting) 

**5. Rename `save` by `add`** 

When you say `create` password, it is already `create` + `save`, same goes for `delete = delete + save` and so on. This just confuses what does `save` exactly means here despite you have explained it in `help`. Point here is first keyword which is after `pygenpass` should be self-explanatory.

**6. Help related improvements**

- Change the order of arguments from `help` according to usage, I have mentioned order in the first suggestion, you can refer+/modify that -- least used should goes down, most used should go up.

- Change value of `help` from `Show this message and exit` to something else.

**7. Copying related improvements**

Please consider this after you accepts first suggestion, PR https://github.com/paint-it/pygenpass/issues/62 already content `copy` and not `copypass` as a pygenpass argument ;)

**8.Security improvements**

Just one atm -- try to encrypt db or store passwords encrypted. I checked more of the functionality side right now, you should consider security improvements later when you feel it is stable enough anytime later.

@mayurilahane  - not going to send further PRs hoping you consider, review and code it yourself.

cc @ganeshhubale

**Comment by ganeshhubale** [comment]
> **1. Remove `pass` suffix from all existing arguments**

@Yadnyawalkya I agree with this solution

> When you run commands like `pygenpass allpass` for example, we already know we are talking about password since `pygenpass` already got that `pass` suffix. You can simply put an argument like `all` (instead of `allpass`) so the user should just type as minimal as he/she can, for example, `pygenpass all`. 
> **2. Meaningful messages after every action completion**
> For example:
> 
> ```
> (py3) [ytale@localhost pygenpass]$ pygenpass createpass
> Enter portal name [None]: 
> Enter email id [None]: 
> Enter portal url [None]: 
> (py3) [ytale@localhost pygenpass]$ 
> ```
> 
> Got one more example:

Similar issue is created #60

> ```
> (py3) [ytale@localhost pygenpass]$ pygenpass createpass
> Enter portal name [None]: 
> Enter email id [None]: 
> Enter portal url [None]: 
> Traceback (most recent call last):
>   File "/home/ytale/opensource/py3/bin/pygenpass", line 11, in <module>
>     load_entry_point('pygenpass==0.1', 'console_scripts', 'pygenpass')()
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/pygenpass-0.1-py3.7.egg/pygenpass/password.py", line 106, in createpass
>     portal_url=portal_url,
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/pygenpass-0.1-py3.7.egg/pygenpass/database.py", line 53, in insert_data
>     (self.portal_name, self.password, self.creation_date, self.email, self.portal_url,),
> sqlite3.IntegrityError: UNIQUE constraint failed: passwords.portal_name
> ```
> You should put a message as `Password saved successfully!` at the end (May be in different color!? )

Agree :+1: 

> 
> **3. No validation require**

:+1: 

> [#45 (comment)](https://github.com/paint-it/pygenpass/issues/45#issuecomment-578410599)

Closing this issue :+1: 

> **5. Rename `save` by `add`**
> 
> When you say `create` password, it is already `create` + `save`, same goes for `delete = delete + save` and so on. This just confuses what does `save` exactly means here despite you have explained it in `help`. Point here is first keyword which is after `pygenpass` should be self-explanatory.

Actually, here ```create``` and ```save``` password are different feature. We can change ```save``` by *add*

**Comment by mayurilahane** [comment]
> These suggestions are really what I think it should do. Feel free to discuss doubts here.
> 
> `<STRONG OPINIONS AHEAD/>`
> 
> **1. Remove `pass` suffix from all existing arguments**
> 
> When you run commands like `pygenpass allpass` for example, we already know we are talking about password since `pygenpass` already got that `pass` suffix. You can simply put an argument like `all` (instead of `allpass`) so the user should just type as minimal as he/she can, for example, `pygenpass all`.
> 
> all, create, add (check 5 before this change), copy (check 8 for more info), show, modify, delete, version

Agree it actually grasp more earlier than previous commands, Thanks!
I think we should replace ```del with delete``` and ```mod with modify``` in my opinion it sounds better.

> **2. Meaningful messages after every action completion**
> 
> For example:
> 
> ```
> (py3) [ytale@localhost pygenpass]$ pygenpass createpass
> Enter portal name [None]: 
> Enter email id [None]: 
> Enter portal url [None]: 
> (py3) [ytale@localhost pygenpass]$ 
> ```
> 
> Got one more example:
> 
> ```
> (py3) [ytale@localhost pygenpass]$ pygenpass createpass
> Enter portal name [None]: 
> Enter email id [None]: 
> Enter portal url [None]: 
> Traceback (most recent call last):
>   File "/home/ytale/opensource/py3/bin/pygenpass", line 11, in <module>
>     load_entry_point('pygenpass==0.1', 'console_scripts', 'pygenpass')()
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/pygenpass-0.1-py3.7.egg/pygenpass/password.py", line 106, in createpass
>     portal_url=portal_url,
>   File "/home/ytale/opensource/py3/lib/python3.7/site-packages/pygenpass-0.1-py3.7.egg/pygenpass/database.py", line 53, in insert_data
>     (self.portal_name, self.password, self.creation_date, self.email, self.portal_url,),
> sqlite3.IntegrityError: UNIQUE constraint failed: passwords.portal_name
> ```
> 
> (Did not searched afterwards, please check if you find more)
> 
> You should put a message as `Password saved successfully!` at the end (May be in different color!? That would be
> 
> **3. No validation require**
> 
> [#45 (comment)](https://github.com/paint-it/pygenpass/issues/45#issuecomment-578410599)
> 
> **4. Table related improvements**
> * Proper table printing -- #59
> * Limit table wrapping till least length of the password so that password would be in single line (the only thing I want to say is -- user should copy password by double click highlighting)
> 
> **5. Rename `save` by `add`**
> 
> When you say `create` password, it is already `create` + `save`, same goes for `delete = delete + save` and so on. This just confuses what does `save` exactly means here despite you have explained it in `help`. Point here is first keyword which is after `pygenpass` should be self-explanatory.

done!
That was really helpful suggestion from a user's point of view.

> **6. Help related improvements**
> 
> * Change the order of arguments from `help` according to usage, I have mentioned order in the first suggestion, you can refer+/modify that -- least used should goes down, most used should go up.
> * Change value of `help` from `Show this message and exit` to something else.
> 
> **7. Copying related improvements**
> 
> Please consider this after you accepts first suggestion, PR #62 already content `copy` and not `copypass` as a pygenpass argument ;)
> 
> **8.Security improvements**
> 
> Just one atm -- try to encrypt db or store passwords encrypted. I checked more of the functionality side right now, you should consider security improvements later when you feel it is stable enough anytime later.
> 
> @mayurilahane - not going to send further PRs hoping you consider, review and code it yourself.

yes sure! 

> cc @ganeshhubale

**Comment by mayurilahane** [comment]
Almost all suggestions are done in spite of 7th and 8th 
#72 will update most of the changes 
Thank you for review @Yadnyawalkya !
